### ISSUE TITLE
Could not find module `symbol-observable`

### ISSUE THREAD

**Issue by bstro** [ember-redux/ember-redux#108]
**Problem**
With the latest release of `ember-redux`, I'm attempting to import `connect` into my file with `import connect from 'ember-redux/components/connect';`. I see the following error in my console: ```Could not find module `symbol-observable` imported from `redux/createStore` ```

node: `4.4.3`
ember-cli: `2.4.3`
ember: `2.4.5`

Any thoughts?

**Comment by toranb** [comment]
@bstro huh, looking at another app I see I've got this ember dependency installed. Can you add this and see if it solves the issue above?

` ember-symbol-observable": "^0.1.2"`

**Comment by bstro** [comment]
Worked! Thanks :)

**Comment by simonihmig** [comment]
I also just got caught by this, with a fresh ember CLI 3.4.0 beta app. Installing `ember-symbol-observable` fixed this. 

`ember-symbol-observable` was not an existing dependency, and even if it were, I don't think you can just rely on that. If `ember-redux` depends on it, it should explicitly say so, by adding it to its own dependencies! This should be reopened IMHO!

**Comment by simonihmig** [comment]
Ah, ok. Thanks for the explanation @toranb! 

The issue I had was that I brought in `ember-redux` as a dependency of another (private) addon. In this case your default blueprint will not be executed, that's why these dependencies were not added to the app...

I can play the same game with my addon, i.e. create a blueprint that calls `addAddonsToProject()` for `ember-redux`. Just wondering, is there a reason why adding those addons as plain dependencies would not work?

**Comment by toranb** [comment]
@simonihmig haha no malice intended I promise :) 

Honestly at the time it appeared to me as if the ember community preferred the `ember install` experience over using npm and package.json directly. In a future release we could reconsider this approach (as shims aren't truly needed like they once were).
