### ISSUE TITLE
connect helper for Ember.Service

### ISSUE THREAD

**Issue by simonihmig** [ember-redux/ember-redux#136]
We just played with our first integration of Redux into Ember (thanks @toranb for your awesome efforts here!), but did something probably quite non-ideomatic: we used the Redux store to manage the state of one central service, not of the overall application. 

I used a (just slightly) modified version of `connect` to bind CPs and actions to a service, rather than a component. Apart from our specific reasons to do that, would you consider this a useful addition to this addon in general?

If so, I could work on a PR for that (cleaning this up and remove code duplication)!

**Comment by toranb** [comment]
@simonihmig awesome that you found redux to be something of value in the ember ecosystem! Not to take away from your success here but the main driver /focus behind this addon is to mirror the [react-redux](https://github.com/reactjs/react-redux) api. Don't let my opinionated view on the subject stop you from experimenting and growing - it's just not something I will bolt into ember-redux at this time.

**Comment by simonihmig** [comment]
Just to make this clear: I did not want to propose introducing some other ways to using redux than before. Part of implementing my use case was to define some computed properties on a service that reflect (readonly) the store's state (and correctly auto-updates). While the `connect` function provides an easy way to accomplish that for components, I did not find one to do the same for a service. So my proposal was to just add that: a helper to define CPs on a service, referring to the redux state.

That being said, I just wondered is there a good reason to not have the state as a CP on the redux service itself, so everywhere you would need some part of that you could inject the service and define a property like `computed.readOnly('redux.state.some.key')`?

**Comment by toranb** [comment]
I'm putting together a full reply to detail out the ember redux approach/ solution here but wanted to ask if you could provide an example of the CP you added to the service you mentioned. I'm trying to grasp the reason you needed to have a service of your own in addition to the redux service (as redux holds all the state in your app)

**Comment by simonihmig** [comment]
Well, we used a CP to generate some "derived state", that is some data to make rendering the original data in the UI convenient, but which is 100% depending only on the "primary" state. So basically the CP is applying a pure function with some domain logic to the redux state, to generate that derived data.

This seemed natural to me, so the redux state remains "lean and clean" and does not contain redundant data. But maybe that's due to my Ember-way of thinking!?

**Comment by toranb** [comment]
Without any additional context I'll take a run at this but let me know if anything below isn't clear/or helpful :)

Above you mentioned defining `readonly` computed properties on a service that reflect the (redux) store's state. In ember-redux we create derived state like this using [reselect](https://github.com/reactjs/reselect). With reselect you define "selectors" that remind me a lot of computed properties in ember*. I use "selectors" to compute state for my container components. The advantage of reselect (like ember CPs) is that they are cached (taking advantage of [memoization](https://en.wikipedia.org/wiki/Memoization)). So if the redux state we use to compute a given "selector" hasn't changed... we don't re-compute this derived state for components (again for much the same reason we use CPs in ember).

To better illustrate this I'll use an example from the ember-redux [guides](http://www.ember-redux.com/guides/) [source](https://github.com/ember-redux/guides/blob/master/app/reducers/restaurants.js). We have a normalized data structure for restaurant => reviews (one-to-many relationship). 

The simplified restaurant(s) data structure

```js
{
  '1': {name: 'taco', reviews: [1, 2, 3]},
  '2': {name: 'salad', reviews: [4, 5]},
  '3': {name: 'yum', reviews: []},
}
```

The simplified reviews data structure

```js
{
  '1': {comment: 'horrible', rating: 1},
  '2': {comment: 'great', rating: 5},
  '3': {comment: 'good stuff', rating : 5},
}
```

To compute the reviews for a given restaurant we would construct a selector called `getReviews`

```js
const all = state => state.restaurants.all;
const selectedId = state => state.restaurants.selectedId;
const reviews = state => state.restaurants.reviews;

export const getSelectedRestaurant = createSelector(
  all,
  selectedId,
  (all, selectedId) => all[selectedId]
);

export const getReviews = createSelector(
  reviews,
  getSelectedRestaurant,
  (reviews, selectedRestaurant) => {
    return selectedRestaurant.reviews.map(reviewId => {
      return reviews[reviewId];
    });
  }
);
```

To answer the second part of your question "is there a good reason to not have the state as a CP on the redux service itself" This is handled for you when you define container components using the connect api. Behind the scenes `stateToComputed` we construct a `readonly` computed property on the component for you that simply returns the (redux) state/or reselect value.

```js
import { connect } from 'ember-redux';
import { getReviews, getSelectedId } from '../reducers/restaurants';

const { get } = Ember;

var stateToComputed = (state) => {
  return {
    reviews: getReviews(state)
  };
};

export default connect(stateToComputed)();
```

So in the example above ^^ you would then have access to `reviews` in your handlebars template. You are able to do this because connect wires up an ember computed property on the fly for each key you return from the `stateToComputed` function.

If you spend a little time with this approach it's my hope that you will conclude 1) you no longer need a service for CPs in addition to the ember-redux service provided and 2) leaning on the connect api will provide the readonly CPs you then yield to presentation components with DDAU in mind.

If I've got it all wrong or you have a use case I've not considered please reach out :)


*Note: one "gotcha" with reselect is that selectors are not lazy evaluated like computed properties

**Comment by simonihmig** [comment]
Hey @toranb, first of all thanks a bunch for walking me through this and giving that thorough feedback, highly appreciated! 👍

I stumbled upon reselect before when exploring the redux ecosystem a bit, and my initial thought was that this could indeed be an alternative way to implement my "derived state" use case, but in a bit less ember-ish and more redux-ish way. Good to have this feeling confirmed!

I guess I have to let this sink in a bit, and get more used to it. So when going all in into the redux way, there is probably indeed no need for state CPs on services. But should I discover some good use cases I will certainly share my thoughts with you!

Thanks again for your time!
