### ISSUE TITLE
Make store customizable for rich 'scoping'

### ISSUE THREAD

**Issue by SUM-PARK** [ember-redux/ember-redux#177]
Hi, after reading nice pointing of store customization(#125)  and answers (#121), I'm still struggling adopting the overall features because of some conventions.

situation : 
- I'm working for an app solution having massive number of pages(300+) and modules using Ember
- redux is a suggested one but not for global usage yet.
- I'm trying to find better state managing pattern using redux from a module in the app.

 So the scope of the store has to be restricted in some modules that I and some colleagues can adopt partially and get rid of it from the memory when we need to. I know it is definitely not the best way to manage multiple stores in an app regarding the original philosophy,  but this is inevitable case.

 After traveling the source, some facts I want to point are :
- there is no store scoping that we cannot specify a root element
- there is convention of folder locations for reducers, enhancers and middlewares 

 For the first one, react has <Provider/> element for scoping, though it is generally applied for the whole app embracing <App/>. With second one, it becomes really frustrating for me when I already have massive folder structure of which I am not in charge and need to be customized.

 I really respect your answers (#125) that you want to make initial kick offs easy and the codes become intuitive. But such powerful conventions can be still a huddle in cases for potential power users.

Wish to have rich discussions and find proper directions together.

**Comment by toranb** [comment]
@SUM-PARK Thanks for writing! I've got a few thoughts that may offer some insight.

This library assumes root level scoping as you mention and in my experience (most) big ember projects are often broken down into many small ember engines. One advantage of this is the scoping isn't completely global and each "engine" gets a root level redux store that operates in isolation.

About folder location for reducers, enhancers, middleware - You can omit using the bundled store and roll any variation of `createStoreWithMiddleware` you find helpful instead as I'm sure you found looking at the store customization documentation. One change in the ember ecosystem that will soon act like a forcing function around this organization is [Module Unification](https://github.com/emberjs/ember.js/issues/16373) and it will no doubt shake up how reducers, middleware and enhancers are organized.

One thing you should note about the point above -I'm the type of person that chooses stability and ease of upgrades for my projects over radical changes that require new versions and a deprecation cycle. Organizing files outside of the "ember wheelhouse" (ie: reducers, middleware) is a challenge right now because none of these "pure functions" are known to the resolver. In addition we've got several competing standards that complicate supporting this well (ie: pods, classic and now module unification).

**Comment by SUM-PARK** [comment]
Thank you for the detailed answer!

Yes, I read [your post about splitting engine](https://www.bignerdranch.com/blog/is-your-ember-app-too-big-split-it-up-with-ember-engines/), but unfortunately I'm in a different environment.

Out solution runs on a single engine with various domain modules (somehow). So with a single Ember (redux) service for the application, we have to construct a wrapping architecture for avoiding conflicts between domains who will use the same store. It is certainly well-taken idea from our situation, but I need to start from a smaller module to see in what way it will work and how well it will work in our structure.

 As we can extract from the previous contexts, single service convention is the only obstacle I have now. Using createStoreWithMiddleware will perfectly help when I can generate my own service which will be used within my module only. But I know changing the code would be both not easy and not 100% needed regarding the ember&redux's own philosophy. I personally hate conventions when it comes to folder structure especially, but it doesn't stop me from respecting and accepting your philosophy because large application is about total different area. 

I will clone the code and customize it for fitting my purpose; it may only contain generating my own service and few additional functions.

But it would be my pleasure to receive any adivce from you or other guys.
